spring:
  mvc:
    favicon:
      enabled: false
  favicon:
    enabled: false
  jpa:
    hibernate:
      ddl-auto: validate
  http:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

logging:
  level:
    net:
      ludeo:
        recikligi: DEBUG

recikligi:
  storageFolder: /tmp
  watson:
    apikey:
  score:
    threshold:
      high: 90
      medium: 70
  daily:
    usage:
      limit: 50