apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: recikligi
spec:
  replicas: 1
  template:
    metadata:
     labels:
        app: recikligi
    spec:
      containers:
      - name: recikligi
        image: @dockerTagname@
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        env:
          - name: RECIKLIGI_WATSON_APIKEY
            valueFrom:
              secretKeyRef:
                name: recikligisecret
                key: apikey
      imagePullSecrets:
      - name: regsecret
---
kind: Service
apiVersion: v1
metadata:
  name: recikligi
spec:
  selector:
    app: recikligi
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: recikligi
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.frontend.rule.type: PathPrefixStrip
spec:
  rules:
  - host: recyclette.k8.wildwidewest.xyz
    http:
      paths:
      - backend:
          serviceName: recikligi
          servicePort: 8080